name = "MyProjectEuler"
uuid = "04758817-3601-4eb2-9b57-0f5881903bb9"
authors = ["fesemeyer <felix.sebastian.meyer@rwth-aachen.de>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
BenchmarkTools = "1.5.0"
DataStructures = "0.18.20"
